version: '3'

services:
  frontend:
    build:
      context: frontend
    depends_on:
      - backend
    command: npm run dev
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
    environment:
      VITE_API_BASE_URL: http://localhost:8000/api
    ports:
      - '3000:3000'

  backend:
    build:
      context: backend
    depends_on:
      - postgres
    command: python src/manage.py runserver 0.0.0.0:8000
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/app
    environment:
      SECRET_KEY: 5a83898f7b41ae679f13a4b580776854
      ENVIRONMENT: development
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
    ports:
      - '8000:8000'

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
