# Generated by Django 3.2.8 on 2021-10-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortening',
            name='target_url',
            field=models.URLField(),
        ),
    ]
