# Generated by Django 3.2.8 on 2021-10-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenings', '0002_alter_shortening_target_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortening',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
