# Generated by Django 3.2.8 on 2021-10-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenings', '0003_alter_shortening_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortening',
            name='author_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
