# Generated by Django 3.2.8 on 2021-10-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenings', '0004_shortening_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortening',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
