# Generated by Django 3.2.8 on 2021-10-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenings', '0005_shortening_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortening',
            name='target_url',
            field=models.TextField(),
        ),
    ]
